version: '3'
services:
  druid:
    image: druidio/example-cluster
    container_name: ajgil-druid
    ports:
      - 8081:8081
      - 8082:8082
  redis:
    image: redis
    restart: always
    volumes:
      - redis:/data
  mysql:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: superset
      MYSQL_DATABASE: superset
      MYSQL_USER: superset
      MYSQL_PASSWORD: superset
    volumes:
      - mysql:/var/lib/mysql
  superset:
    build: superset/
    container_name: t2c-superset
    image: t2c/druid-superset
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
volumes:
  mysql:
    external: false
  redis:
    external: false